In [12]:
# 导入 pandas 库并将其简化为 pd
import pandas as pd
# 读取口罩厂数据，文件路径为 './工作/mask_data.csv'，并将编码格式设置为 'utf-8'
mask_data = pd.read_csv('./工作/mask_data.csv', encoding = 'utf-8')
# 查看 mask_data
mask_data

,订单编号,日期,省,订单量,单价,销售额
0,87af-48e5-8bed-c5dcf9ecc172,2020-01-01,广东,0.0,30.0,0.0
1,535a-4eca-8fa0-9cc54c66e11d,2020-01-01,河南,0.0,30.0,0.0
2,a56d-4415-ad6e-020cdb154c35,2020-01-01,湖北,1.0,30.0,30.0
3,535a-4eca-8fa0-9cc54c66e11d,2020-01-01,河南,0.0,30.0,0.0
4,535a-4eca-8fa0-9cc54c66e11d,2020-01-01,河南,0.0,30.0,0.0
...,...,...,...,...,...,...
101937,6339-43f4-a12b-7b57d1ce3a48,NaN,NaN,NaN,NaN,NaN
101938,5e43-41c2-8696-fd5909cc98a4,NaN,NaN,999999999.0,999999999.0,999999999.0
101939,824c-4f2b-af43-038938d2db46,NaN,NaN,999999999.0,999999999.0,999999999.0
101940,1cf0-483a-ab11-0cebc6406c78,NaN,NaN,0.0,NaN,0.0
101941,8318-43df-9d34-0656d9eb759a,NaN,NaN,0.0,NaN,0.0

In [13]:
mask_data

,订单编号,日期,省,订单量,单价,销售额
0,87af-48e5-8bed-c5dcf9ecc172,2020-01-01,广东,0.0,30.0,0.0
1,535a-4eca-8fa0-9cc54c66e11d,2020-01-01,河南,0.0,30.0,0.0
2,a56d-4415-ad6e-020cdb154c35,2020-01-01,湖北,1.0,30.0,30.0
3,535a-4eca-8fa0-9cc54c66e11d,2020-01-01,河南,0.0,30.0,0.0
4,535a-4eca-8fa0-9cc54c66e11d,2020-01-01,河南,0.0,30.0,0.0
...,...,...,...,...,...,...
101937,6339-43f4-a12b-7b57d1ce3a48,NaN,NaN,NaN,NaN,NaN
101938,5e43-41c2-8696-fd5909cc98a4,NaN,NaN,999999999.0,999999999.0,999999999.0
101939,824c-4f2b-af43-038938d2db46,NaN,NaN,999999999.0,999999999.0,999999999.0
101940,1cf0-483a-ab11-0cebc6406c78,NaN,NaN,0.0,NaN,0.0
101941,8318-43df-9d34-0656d9eb759a,NaN,NaN,0.0,NaN,0.0

In [14]:
clear

In [15]:
import os
os.system('pwd')

/Users/zhangze/Desktop/python improve/数据科学/第三课

0